### ISSUE TITLE
The latest submit generate artifacts 

### ISSUE THREAD

**Issue by adicirstei** [incompl/boxbox#33]
Hi,

I'm new to Box2D and I find your project really useful. There is one issue, though. The latest submit to github is producing artifacts on rendering.

I'm not sure where the issue resides but it must be easy for you to find. To get an idea what I'm talking about, compare the version you are using in your demos and the one in source. I tried on latest versions of Firefox and Chrome.

Here are the links:
http://incompl.github.io/boxbox/boxbox/demos/chain/chain.html
https://rawgithub.com/incompl/boxbox/master/demos/chain/chain.html

**Comment by incompl** [comment]
Fixed it!

**Comment by incompl** [comment]
This happened because I merged a bogus pull request without testing it. https://github.com/incompl/boxbox/commit/64b0e0f155c5c4789967528e8c06f165d8149b9a

**Comment by adicirstei** [comment]
Amazingly fast!

Thanks!
